---
- name: "Install Java"
  ansible.builtin.apt:
    name:  'default-jre'
    state: 'present'

- name: 'Check if Solr is already installed'
  ansible.builtin.stat:
    path: '/etc/init.d/solr'
  register: 'solr_service'

- name: 'Install Solr'
  ansible.builtin.include_tasks:
    file: 'install.yml'
  when: solr_service.stat.exists == False

- name: 'Apache Configuration'
  ansible.builtin.copy:
    src:  'apache.conf'
    dest: '/etc/apache2/sites-enabled/conf.d/solr.conf'
  notify: 'apache_restart'
...
